#!/bin/bash
#SBATCH --job-name=4a_pc_impute_relateds            # Job name
#SBATCH --mail-type=END,FAIL                        # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --ntasks=4                                  # Run on a single CPU
#SBATCH --n-tasks-per-node=4                        # number of tasks running per node
#SBATCH --cpus-per-task=12                          # number of cpus per task
#SBATCH --mem=20gb                                  # Job memory request
#SBATCH --time=12:00:00                             # Time limit hrs:min:sec
#SBATCH --account=youraccount                       # account used for the job

# load modules in..
module add apps/plink2

# load variables in..
pfile_prefix=$1
pc_prefix=$2
output_name=$3

# king variables
# king_table=${4}.kin0
# king_keep=${4}.king.cutoff.in.id
king_drop=${4}.king.cutoff.out.id

# allele weights generated by plink2 --pca allele-wts $pc_number vcols=chrom,ref,alt
allele_weights=$5

# Get count of columns, so you can work out col 6 -> last col for --score-col-nums
colcount=$(awk '{print NF}' $allele_weights | sort -nu | tail -n 1)

# re generate new PCs which include relateds. done for all together rather than just subet and merging.
plink2 \
    --pfile $pfile_prefix \
    --read-freq $pc_prefix.acount \
    --score $allele_weights 2 5 header-read no-mean-imputation variance-standardize \
    --score-col-nums 6-${colcount} \
    --out $output_name

    # --keep $king_drop \